### ISSUE TITLE
No support for other USB devices 

### ISSUE THREAD

**Issue by karniv00l** [speeduino/SpeedyLoader#10]
I assume that this is still in progress, but currently upload will fail for other / not specified serial converters.
In my case it's `CH340` on a cheap Mega clone.

https://www.the-sz.com/products/usbid/index.php?v=0x1A86&p=0x7523

```js
{
  locationId: "14300000"
  manufacturer: undefined
  path: "/dev/tty.usbserial-1430"
  pnpId: undefined
  productId: "7523"
  serialNumber: undefined
  vendorId: "1a86"
}
```

**Comment by noisymime** [comment]
Still a WIP yep. I need to go through and add the other VID/PIDs that are known to be used with mega2560 clones (such as the various ch340 versions) but also add a catch-all that defaults to the mega if unknown. 

Should be coming in the next day or 2
